on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write

    name: Publish to GitHub Pages
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.1"
          elixir-version: "1.17.2"

      - run: mix do local.rebar --force, local.hex --force, deps.get

      - run: mix tableau.build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./_site"

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4